# Generated by Django 3.2.9 on 2021-12-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_body',
        ),
    ]
