# Generated by Django 3.2.9 on 2021-12-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_body_comment_comment_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
